name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: TOOL

jobs:
  build:
    name: Build
    runs-on: macos-12
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v3
      - name: CI Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh) && eval "$src" || exit 1

      - run: make
      - run: zip -qry -FS dmidecode-mac-$(cat version.h | cut -f2 -d'"').zip dmidecode

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: dmidecode-mac-*.zip
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dmidecode-mac-*.zip
          tag: ${{ github.ref }}
          file_glob: true
